name: jobs

on:  
  push:
  
jobs:
  concurrency-job2:
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
        - run: Sleep 15
        
  concurrency-job1:
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
        - run: Sleep 15

  deploy-job:
    name: deploy job
    runs-on: ubutntu-latest
    needs: build-job
    steps:
      - name: test build output
        run: echo ${{ needs.build-job.output }}

        
  build-job:
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOut }}
    name: build job
    runs-on: ubutu-latest
    container:
      image: oven/bun:slim
    steps:
      - name: define output variable
        id: buildstep
        run: 
          bunver=$(bun --version)
          echo "buildOut=$bunver".. "$GITHUB_OUTPUT"

